### ISSUE TITLE
Support SHA-3

### ISSUE THREAD

**Issue by rugk** [westberliner/owncloud-checksum#10]
Integrating [SHA-3](https://en.wikipedia.org/wiki/SHA-3) support would be nice.

**Comment by westberliner** [comment]
Done :) and pushed to apps.[nextcloud|owncloud].com or downloud it directly.

**Comment by rugk** [comment]
WOW, that was fast… 💪

**Comment by rugk** [comment]
[But…](https://github.com/westberliner/owncloud-checksum/commit/eeae274621553d55e08221f86bd3d91930fe7b60) ah you've added sSHA-384 support. Not bad, but not what this issue was about. It was really too fast to solve…
SHA-3 is a whole new algorithm, similarly to what SHA-2 (i.e. SHA-256, SHA-512, …) is. See the Wikipedia article I've linked.

**Comment by westberliner** [comment]
You got lucky cause I fixed some minor issues on checksum right in that moment :) To bad that this is the wrong crypto. 

PHP cannot create sha3 out of the box - at least till 7.0.x.

I found this extension https://github.com/strawbrary/php-sha3
or this library https://github.com/0xbb/php-sha3. But I am not a crypto guy so i cannot evaluate if these libraries are good implementations of sha3. 

I can implement this in the future if php can generate sha3 more out of the box. If you cannot wait just fork my project or do have any more hints?

**Comment by westberliner** [comment]
Of course they implemented in PHP 7.1 XD

I had this idea too. To get the algo-list via ajax. But the list is quiet long. So i would want to create a admin settings page for the admin to preselect. In the next version then.

**Comment by rugk** [comment]
You don't have to get all algos, only the supported ones (and ones used in your project), but I think I get your idea. You could of course make all algos available to the admin.

**Comment by DJCrashdummy** [comment]
> ... i would want to create a admin settings page for the admin to preselect.

@westberliner if this gets implemented, the icing on top would be to sort them... (but only if it is not too much work!)
