### ISSUE TITLE
Installation from app store fails, on OC 9.1.5

### ISSUE THREAD

**Issue by tedstrauss** [westberliner/owncloud-checksum#11]
I get this error message when trying to install using the app store:

`App can't be installed because the version in info.xml is not the same as the version reported from the app store`

I've tried cloning the repo in the apps/ folder, and modifying values in the info.xml file.
It didn't fix it.

Any suggestions?

**Comment by tedstrauss** [comment]
As a work around, I commented out the version check from the installer code. The app appears to have installed normally.

lib/private/Installer.php:407 >>>
```
/*if(isset($data['appdata']['version']) && $version<>trim($data['appdata']['version'])) {
     OC_Helper::rmdirr($extractDir);
     throw new \Exception($l->t("App can't be installed because the version in info.xml is no$
}*/
```

**Comment by westberliner** [comment]
Hi, 

thanks for your feedback. I will try to fix this issue this week.

**Comment by westberliner** [comment]
I submitted finally the app into the new marketplace: https://marketplace.owncloud.com/apps/checksum
