### ISSUE TITLE
What are people using this app for? Is my use case supported?

### ISSUE THREAD

**Issue by tedstrauss** [westberliner/owncloud-checksum#12]
I have a specific use case for this OC app, and wondering whether it's supported. And wondering what else people have used this app for.

Use case: file backup verification

Users will back up data from their local machines to OC, and wish to use checksum to verify data integrity. I suppose the files would need checksums already...

**Comment by westberliner** [comment]
Hi,

I intended to use it the other way around but this is also possible since a hash from the same file should always be the same. So just generate a hash on your local machine and check it against the output of this app.

In short your use-case matches with this app :)
