### ISSUE TITLE
Doesn't work in owncloud 9.1.0

### ISSUE THREAD

**Issue by bryceml** [westberliner/owncloud-checksum#2]
It doesn't seem to work in owncloud 9.1.0.  Are you still maintaining this app?  This would be really useful for me.

**Comment by westberliner** [comment]
Sry, for the late answer. I'll can look into if you didn't find any alternativ.

**Comment by bryceml** [comment]
I haven't found an alternative, so that would be great.

**Comment by westberliner** [comment]
alright then :) i'll look into and try to fix it.

**Comment by westberliner** [comment]
The app is good to go for owncloud version 9. I changed the ui a little bit. I moved the feature into the detail view. Keep me updated if it es working ... or not :) 

commit 58080ba7aa61111161ad4c08d1b5b8b5015d2a3e

**Comment by bryceml** [comment]
It works, thanks.
