### ISSUE TITLE
nextcloud13 install

### ISSUE THREAD

**Issue by mesamoo** [westberliner/owncloud-checksum#26]
nextcloud 13 rc2 on linux/apache/php7.2

when trying to enable checksum using nextcloud, nextcloud reports failure. 
Message reported by nextcloud is "Extracted app checksum has more than 1 folder"

I was able to hand install, downloaded from Nextcloud App Store
extracted archive and copied the checksum folder to nextcloud/apps.
changed permissions
enabled in nextcloud apps settings

One thought is that the additional (maxOS) file "._checksum" in the archive may have been the cause of the issue

**Comment by mesamoo** [comment]
I see a new release 0.3.6 listed on the insights page which has not reached the app store yet, perhaps the issue is addressed in that release

**Comment by westberliner** [comment]
I rereleased the package. The App Store complains about the changed URL. I think it will take some minutes for the update.
It's true. the ._ files are causing this.

As a side note: COPYFILE_DISABLE=1 mitigate tarballing dot-files.

**Comment by westberliner** [comment]
Works for me now. Hope for you too.
