### ISSUE TITLE
publish current version via nextcloud app-store

### ISSUE THREAD

**Issue by DJCrashdummy** [westberliner/owncloud-checksum#29]
is it possible to publish the current version (something >0.3.5) via the nextcloud app-store?

yes i've read #25 and #24, but https://github.com/westberliner/owncloud-checksum/issues/26#issuecomment-361034535 is still valid: in the [app-store](https://apps.nextcloud.com/apps/checksum) (just scroll down and have a look) there is still 0.3.5 the latest version and so within nextcloud checksum appears to be incompatible with NC13.

---
btw: just want to mention it, because it seems very interesting resp. strange to me...
in the nextcloud app-store the latest version is 0.3.5 and therefore also updating within nextcloud isn't possible and checksum is deactivated after upgrading to NC13 due to [max-version of the app](https://github.com/westberliner/owncloud-checksum/blob/v0.3.5/appinfo/info.xml#L32).
so far so good... BUT why is a NC13-compatible version (0.3.5) listed at the [app-store-site](https://apps.nextcloud.com/apps/checksum)?!? ...and i guess because of that also the nice little app [ Can I update?](https://apps.nextcloud.com/apps/caniupdate) says checksum should already be available for NC13.

@westberliner do you have any idea about this behavior? or if not and it is an issue of nextcloud, already pinged the nextcloud-guys?

**Comment by westberliner** [comment]
true, i will look into it.

**Comment by DJCrashdummy** [comment]
it got even more interesting...:
at another instance for testing running NC 13.0.1.1 now i saw checksum 0.3.5 installed and active! - i have no clue how it got there (except via the nextcloud app-store) since i'm pretty sure i didn't sideload any app at this instance.

because of that i had a look at the nextcloud app-store:
the link behind version 0.3.5 is https://github.com/westberliner/owncloud-checksum/releases/download/v0.3.6.1/checksum.tar.gz and after downloading, the info.xml shows `<version>0.3.5</version>` and `max-version="13"`... **so i guess the problem is releasing version >0.3.5 without raising the verion in the info.xml.**

so the explanation for my situation is:
on the one instance i've got the "old 0.3.5" marked as incompatible with NC13 and on the other instance i loaded the "new 0.3.5" compatible with NC13. - completely uninstalling the "old 0.3.5" and installing the "new 0.3.5" from the app-store again solved the situation.

**--> i guess releasing a new version >0.3.6.1 with a correct info.xml will solve the situation for all users.**

**Comment by westberliner** [comment]
thx for your work. i will update my appinfo in the evening and release the plugin again.

**Comment by westberliner** [comment]
I have released the version 0.4. I got an error for my xml. It was possible to add a letter in the beginning of the version but not anymore I guess. I think this could be the cause. Anyway I hope now everything should be working again.

I'll keep this issue open for a few days just in case.

**Comment by zertrin** [comment]
Just received the automatic notification to upgrade checksum to 0.4.0 on NC13 and https://apps.nextcloud.com/apps/checksum lists 0.4.0 for every NC versions. So it seems to have worked.
