### ISSUE TITLE
Checksum not compliant with Nextcloud 15

### ISSUE THREAD

**Issue by g33k247** [westberliner/owncloud-checksum#33]
Upgrade to NC15 automatically disabled checksum app. Unable to find in app catalog.

**Comment by violoncelloch** [comment]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by nextgen-networks** [comment]
@westberliner Please consider this PR: https://github.com/westberliner/owncloud-checksum/pull/34
If everything went fine you could publish this to NC appstore too.
Thanks mate!

**Comment by stratege1401** [comment]
yes, please ... very usefull app

**Comment by violoncelloCH** [comment]
Whohoo, there is a new release supporting NC 15! Thank you @westberliner

**Comment by westberliner** [comment]
thx to @nextgen-networks

**Comment by danger89** [comment]
Strange it will still disable this app during upgrade to 15 :\
