### ISSUE TITLE
No icon for the Checksum-tab in the sidebar.

### ISSUE THREAD

**Issue by NiklasOlofsson** [westberliner/owncloud-checksum#37]
No icon for the Checksum tab. Looks a bit odd. :)

![cap2](https://user-images.githubusercontent.com/4583709/55088533-2a8d2180-50ac-11e9-87d3-38982b338ef9.png)

**Comment by confusedguy9** [comment]
See #36

**Comment by westberliner** [comment]
Merged #36. Release is on its way.
