### ISSUE TITLE
Owncloud update downloads a wrong checksum app with higher version number

### ISSUE THREAD

**Issue by e-alfred** [westberliner/owncloud-checksum#6]
Hello,

if Owncloud gets updated, it automatically checks for new apps in the store and updates to a different app with a higher version number from here:

https://apps.owncloud.com/content/show.php/Checksum+MD5?content=174662

To solve this, maybe a higher version number would be needed.

Thank you

**Comment by westberliner** [comment]
I will look into that. Thx for mentioning.

**Comment by westberliner** [comment]
I updated the version number along with the current owncloud version in apps.owncloud.com. I hope this helps. If not, just reopen this issue.
