### ISSUE TITLE
Nextcloud-installation and App-Update fails

### ISSUE THREAD

**Issue by DJCrashdummy** [westberliner/owncloud-checksum#7]
the nextcloud-installation _(In your Instance, simply navigate to »Apps«, choose the category »Files«, find the Checksum app and enable it.)_ does not work:
> Client error response [url] https://herzberg-digital.de/checksum.tar.gz [status code] 404 [reason phrase] Not Found

and after a manual installation (of the latest release) it shows immediately an update, but it can't be applied. the only way to have everything as it should be, is to install the master manually.

**and by the way:** there are only releases for the old version with just MD5 and no choice (like it was installed within the nextcloud-apps just a week ago) present.

**Comment by Dracon23** [comment]
Can confirm this. 

Error is the same, Nextcloud 11.0.2

**Comment by EpicLPer** [comment]
Error 404 on the install URL given

**Comment by MariusBluem** [comment]
I can reproduce `Client error response [url] https://herzberg-digital.de/checksum.tar.gz [status code] 404 [reason phrase] Not Found`

**Comment by DJCrashdummy** [comment]
as you can see at the app-store (https://apps.nextcloud.com/apps/checksum) the links for checksum 0.3.1 for every nexcloud version are offline.

with nextcloud 10 and older it can be downloaded because the owncloud app-store is used and it gathers the archive direct from the github-master, but then it can't be installed because of the known "github-master-problem"...

**Comment by DJCrashdummy** [comment]
it seems that https://herzberg-digital.de/checksum.tar.gz is online again...!
