### ISSUE TITLE
Which hashes are possible?

### ISSUE THREAD

**Issue by rugk** [westberliner/owncloud-checksum#8]
Could you expand the README/description with a list of hashes this add-on supports?

**Comment by DJCrashdummy** [comment]
as you can see in the code (https://github.com/westberliner/owncloud-checksum/blob/master/js/checksum.tabview.js#L35-L39) for now it is possible to choose between `crc32`, `md5`, `sha1`, `sha256` and `sha512`.

but you are right a little bit more in the info.xml-description and maybe additional in the readme would not hurt.

**Comment by westberliner** [comment]
I updated the readme.

**Comment by DJCrashdummy** [comment]
@westberliner: thank you very much for your update!

btw: the icing on the cake would be a link in the /appinfo/info.xml to the readme, maybe like...
```
<documentation>
	<user>https://github.com/westberliner/owncloud-checksum/blob/master/README.md</user>
</documentation>
```

**Comment by westberliner** [comment]
Icing is done :) I am not proud of the output on apps.nextcloud.com but at least it shows something.

**Comment by DJCrashdummy** [comment]
awesome! now the very good description is also displayed within nextcloud.
yes... at the webpage it looks not really polished (i don't know why), but it is better than nothing. ;-)
