### ISSUE TITLE
Installation fails, 404 error

### ISSUE THREAD

**Issue by rugk** [westberliner/owncloud-checksum#9]
The installation of this add-on fails as https://herzberg-digital.de/checksum.tar.gz returns a 404 error.

**Comment by DevSidious** [comment]
I can confirm this.

Client error response [url] https://herzberg-digital.de/checksum.tar.gz [status code] 404 [reason phrase] Not Found

Nextcloud 11.0.2 stable (11.0.2.7)

**Comment by DJCrashdummy** [comment]
this was already mentioned: https://github.com/westberliner/owncloud-checksum/issues/7

**Comment by rugk** [comment]
Online again, nice. But I hope @westberliner, you do not use MD5 anymore as mentioned by @DJCrashdummy in https://github.com/westberliner/owncloud-checksum/issues/7#issue-211052850. That would be really ironic for a checksum package… :laughing: 
So use SHA-256 at least.

**Comment by DJCrashdummy** [comment]
@rugk: no deal... i've read it and it was a nice laugh before the question marks rose in my head. ;-)

**Comment by westberliner** [comment]
Hi and sry, 

I had issues with my Server a while back. I will update my github mailsettings. I saw this issue after you mentioned my name.

**Comment by DJCrashdummy** [comment]
@westberliner: why not direct use a github-release for the nextcloud-store?

**Comment by westberliner** [comment]
Good idea, i will change it together with a better description (#8).
